### ISSUE TITLE
Please validate/ update the overview section in the main ReadMe

### ISSUE THREAD

**Issue by FBoucher** [MSDEVMTL/GlobalAzureBootcamp2018#2]
I added an overview section in the main ReadMe.md

Please validate/ update the overview section in the [main ReadMe](https://github.com/MSDEVMTL/GlobalAzureBootcamp2018/blob/master/README.md)

ref: https://github.com/MSDEVMTL/GlobalAzureBootcamp2018#overview-of-the-day

**Comment by slapointe** [comment]
What you propose is better presented... we'll keep in this way. I will only add the link to steps but keep your format.
