### ISSUE TITLE
Azure PowerShell code is more for Windows, what about Mac & Linux?

### ISSUE THREAD

**Issue by slapointe** [MSDEVMTL/GlobalAzureBootcamp2018#4]
I received a comment from an attendee wondering how he would attend the day since he was running MacOS.

Might be good thing to consider converting AzureRm PowerShell to AzureCLI

**Comment by guybarrette** [comment]
The solution would have to be converted to .NET Core so it can be used with VS Mac.  Also, I don't think you can remote debug using VS Mac.  Not a big thing since it's only 10-15min in Step 6.

**Comment by slapointe** [comment]
PowerShell will stay for this year's code. We'll keep in mind to be more compatible in future GAB content we produce.
