### ISSUE TITLE
Step2/Invoke-Provisioning.ps1 fails if Get-AzureRmADUser UserPrincipalName != Account email

### ISSUE THREAD

**Issue by patrickceg** [MSDEVMTL/GlobalAzureBootcamp2018#8]
Hello!

I'd just like to report the issue I had during today's meetup/GAB event. (Thanks for all the help troubleshooting!)

So my Azure account and my "Active Directory" user name are not the same:

```PS C:\WINDOWS\system32> Login-AzureRmAccount
Account          : [snip]@outlook.com
[snip]
Environment      : AzureCloud
```

My account has an outlook.com e-mail address.

```
PS C:\WINDOWS\system32> Get-AzureRmADUser

UserPrincipalName                                                   DisplayName Id                                   Type
-----------------                                                   ----------- --                                   --
[snip]_hotmail.com#EXT#[snip].onmicrosoft.com [display name snipped]   [Azure GUID snipped] User
```

My "UserPrincipalName" has my much older hotmail.com address. (The hotmail address obviously came first, and the outlook.com address is an alias - both of them work for me to log into my Microsoft account, and sending e-mail to either one puts the mail into the same inbox.

The script fails in this block:

```
$aduser = Get-AzureRmADUser -UserPrincipalName $user
if(-not $aduser) {
  $adusers = Get-AzureRmADUser
  # try to resolve the user as an external user in tenant.
  $aduser = $adusers | ? UserPrincipalName -Match ($user -replace '@', '_')
}
if($aduser.Id) {
  $objectId = $aduser.Id
}
```

So the first attempt to Get-AzureRmADUser tries to get a user with exactly my @outlook.com address, which fails because that does not exist for me. It then fails over to try to do a string match, but again that fails because the strings cannot match. (Doing a string comparison with X_outlook and Y_hotmail returns false.)

My workaround was to hard-code the Get-AzureRmADUser replacing $user with exactly the UserPrincipleName that I have (the hotmail address).

Steps to reproduce:

1. Make sure the Get-AzureRmADUser returns a UserPrincipalName that is not equal to the account e-mail address of the Azure account (Note I don't know how I got into this situation to begin with! It's possible I originally signed up for Azure years ago with the Hotmail address and my subscription is had the Outlook address, but I wouldn't really know). 
2. Go through the entire step 1 for of the lab (which should succeed because that script doesn't do the same check.)
3. Go through step 2 up to and including the step for the provisioning with the PowerShell script.

Expected result: Provisioning succeeds
Actual result: 

```
PS C:\gab2018\Step2> & .\Invoke-Provisioning.ps1

Unable to resolve account [snip]@outlook.com
At C:\gab2018\Step2\Invoke-Provisioning.ps1:42 char:11
+           throw ('Unable to resolve account {0}' -f $Account.Id)
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to resol...s[snip]@outlook.com:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to resolve account [snip]@outlook.com
```

**Comment by slapointe** [comment]
Since this issue seems to be very narrow and limited and you were able to workaround it easily. I will go ahead and close the issue.
